# Generated by Django 6.0.3 on 2026-03-21 07:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Consumer', 'Consumer'), ('Vendor', 'Vendor'), ('Admin', 'Admin')], db_index=True, default='Consumer', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended')], default='Active', max_length=20)),
                ('is_vendor_approved', models.BooleanField(default=False)),
                ('login_attempts', models.IntegerField(default=0)),
                ('account_locked', models.BooleanField(default=False)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('permanently_locked', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_mode', models.BooleanField(default=False)),
                ('hygiene_score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('freshness_score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('service_score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True, max_length=1000, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('consumer', models.ForeignKey(blank=True, limit_choices_to={'role': 'Consumer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FlaggedReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved'), ('Dismissed', 'Dismissed')], default='Pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('flagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagged_reviews', to=settings.AUTH_USER_MODEL)),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='core.rating')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='RatingAlgorithmConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hygiene_weight', models.DecimalField(decimal_places=3, default=0.4, max_digits=4)),
                ('freshness_weight', models.DecimalField(decimal_places=3, default=0.35, max_digits=4)),
                ('service_weight', models.DecimalField(decimal_places=3, default=0.25, max_digits=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'Admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rating Algorithm Config',
            },
        ),
        migrations.CreateModel(
            name='VendorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=255)),
                ('location', models.CharField(db_index=True, max_length=255)),
                ('kebs_license', models.CharField(max_length=100, unique=True)),
                ('meat_types', models.CharField(default='Mixed', max_length=200)),
                ('price_range', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('profile_image', models.URLField(blank=True, null=True)),
                ('hygiene_score', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=3)),
                ('freshness_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('service_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('overall_score', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=3)),
                ('total_ratings', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(limit_choices_to={'role': 'Vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Details',
            },
        ),
        migrations.AddField(
            model_name='rating',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_ratings', to='core.vendordetails'),
        ),
        migrations.CreateModel(
            name='VendorReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='core.rating')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('kebs_license', models.CharField(max_length=100)),
                ('meat_types', models.CharField(default='Mixed', max_length=200)),
                ('price_range', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=20)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_date'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='core_user_role_73872d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='core_user_email_38052c_idx'),
        ),
        migrations.AddIndex(
            model_name='vendordetails',
            index=models.Index(fields=['location'], name='core_vendor_locatio_25af40_idx'),
        ),
        migrations.AddIndex(
            model_name='vendordetails',
            index=models.Index(fields=['hygiene_score'], name='core_vendor_hygiene_3a64a4_idx'),
        ),
        migrations.AddIndex(
            model_name='vendordetails',
            index=models.Index(fields=['overall_score'], name='core_vendor_overall_00db1b_idx'),
        ),
        migrations.AddIndex(
            model_name='vendordetails',
            index=models.Index(fields=['meat_types'], name='core_vendor_meat_ty_381af3_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['vendor', 'timestamp'], name='core_rating_vendor__31bdfd_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['consumer'], name='core_rating_consume_88697f_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['is_flagged'], name='core_rating_is_flag_9a4986_idx'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(condition=models.Q(('anonymous_mode', False)), fields=('vendor', 'consumer'), name='unique_consumer_vendor_rating'),
        ),
        migrations.AddIndex(
            model_name='vendorrequest',
            index=models.Index(fields=['status'], name='core_vendor_status_e8e436_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorrequest',
            index=models.Index(fields=['submitted_date'], name='core_vendor_submitt_348636_idx'),
        ),
    ]
