# Generated by Django 6.0.3 on 2026-03-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shopnamechangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendordetails',
            name='meat_photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
